# Generated by Django 4.0.3 on 2022-09-06 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('fromDate', models.CharField(max_length=10, null=True)),
                ('toDate', models.CharField(max_length=10, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationName', models.CharField(max_length=255, null=True)),
                ('fromDate', models.CharField(max_length=10, null=True)),
                ('toDate', models.CharField(max_length=10, null=True)),
                ('percentage', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('NA', 'Not Disclosed')], max_length=2)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/')),
                ('addressDetails', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.address')),
                ('projects', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.projects')),
                ('qualificiations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.qualifications')),
                ('workExeperience', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
