# Generated by Django 4.1 on 2022-09-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
