# Generated by Django 4.1 on 2022-09-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0002_alter_experience_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="workExeperience",
            new_name="workExperience",
        ),
    ]
