# Generated by Django 4.1 on 2022-09-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0003_rename_workexeperience_user_workexperience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="qualificiations",
            new_name="qualifications",
        ),
    ]
