# Generated by Django 4.1 on 2022-09-08 01:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("employeeApp", "0004_rename_qualificiations_user_qualifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
